console.log('Hello');
console.log('Hello');
// let a = 5
try {
    console.log(a);
} catch(err) {
    console.log('caught an error .... a is not defined');
    console.log(err);
    
}

console.log('Hello2');
console.log('Hello2');
console.log('Hello2');